# Generated by Django 5.1.7 on 2025-07-10 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_modulecategory_alter_module_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['module', 'order', 'title'], 'verbose_name': 'Article Reference', 'verbose_name_plural': 'Article References'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['module', 'order', 'title'], 'verbose_name': 'Learning Content', 'verbose_name_plural': 'Learning Contents'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['category__name', 'title'], 'verbose_name': 'Learning Module', 'verbose_name_plural': 'Learning Modules'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['module', 'order', 'title'], 'verbose_name': 'Programming Task', 'verbose_name_plural': 'Programming Tasks'},
        ),
        migrations.AlterModelOptions(
            name='usertaskprogress',
            options={'ordering': ['user', 'task'], 'verbose_name': 'User Task Progress', 'verbose_name_plural': 'User Task Progress Entries'},
        ),
        migrations.AlterField(
            model_name='article',
            name='module',
            field=models.ForeignKey(help_text='Module this article belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='elearning.module', verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='article',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of articles within the module', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Descriptive title for the article', max_length=255, verbose_name='Article Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(help_text='URL to the external article or resource', max_length=500, verbose_name='Article URL'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description or text content', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='content',
            name='module',
            field=models.ForeignKey(help_text='Module this content belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='elearning.module', verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of content within the module (0 = first)', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='content',
            name='supplementary_title',
            field=models.CharField(blank=True, help_text='Optional additional title or subtitle', max_length=200, null=True, verbose_name='Supplementary Title'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(help_text='Descriptive title for this content item', max_length=255, verbose_name='Content Title'),
        ),
        migrations.AlterField(
            model_name='content',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional URL to video content (YouTube, Vimeo, etc.)', max_length=500, null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='module',
            name='category',
            field=models.ForeignKey(help_text='The category this module belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='elearning.modulecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If True, the module is accessible to all authenticated users. If False, access is restricted based on ModuleAccess entries.', verbose_name='Public Access'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(help_text='The unique title of the learning module', max_length=200, unique=True, verbose_name='Module Title'),
        ),
        migrations.AlterField(
            model_name='moduleaccess',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when access was granted', verbose_name='Granted At'),
        ),
        migrations.AlterField(
            model_name='moduleaccess',
            name='module',
            field=models.ForeignKey(help_text='Module that user has been granted access to', on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='elearning.module', verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='moduleaccess',
            name='user',
            field=models.ForeignKey(help_text='User granted access to the module', on_delete=django.db.models.deletion.CASCADE, related_name='module_access_entries', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='modulecategory',
            name='name',
            field=models.CharField(help_text='Unique name for this module category', max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='supplementarycontent',
            name='content',
            field=models.ForeignKey(help_text='Content item this supplementary material belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_contents', to='elearning.content', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='supplementarycontent',
            name='label',
            field=models.CharField(help_text='Descriptive label for the supplementary link', max_length=200, verbose_name='Link Label'),
        ),
        migrations.AlterField(
            model_name='supplementarycontent',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of supplementary links within content', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='supplementarycontent',
            name='url',
            field=models.URLField(help_text='URL to the supplementary resource', max_length=500, verbose_name='Resource URL'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Detailed instructions and requirements for the task', verbose_name='Task Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('Einfach', 'Easy'), ('Mittel', 'Medium'), ('Schwer', 'Hard')], default='Mittel', help_text='Difficulty level for student guidance', max_length=10, verbose_name='Difficulty Level'),
        ),
        migrations.AlterField(
            model_name='task',
            name='hint',
            field=models.TextField(blank=True, help_text='Optional hint to help students solve the task', null=True, verbose_name='Hint'),
        ),
        migrations.AlterField(
            model_name='task',
            name='module',
            field=models.ForeignKey(help_text='Module this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='elearning.module', verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of tasks within the module', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='task',
            name='test_file_path',
            field=models.CharField(blank=True, help_text="Relative path from the 'elearning' app directory to the python file containing unittest cases. E.g., 'task_tests/module1/task10_tests.py'", max_length=255, verbose_name='Test File Path'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Descriptive title for the programming task', max_length=255, verbose_name='Task Title'),
        ),
        migrations.AlterField(
            model_name='usertaskprogress',
            name='completed',
            field=models.BooleanField(default=False, help_text='Whether the user has completed this task', verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='usertaskprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the task was marked as completed', null=True, verbose_name='Completed At'),
        ),
        migrations.AlterField(
            model_name='usertaskprogress',
            name='task',
            field=models.ForeignKey(help_text='Task being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='elearning.task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='usertaskprogress',
            name='user',
            field=models.ForeignKey(help_text='User whose progress is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='usertaskprogress',
            index=models.Index(fields=['user', 'completed'], name='elearning_u_user_id_dee084_idx'),
        ),
        migrations.AddIndex(
            model_name='usertaskprogress',
            index=models.Index(fields=['task', 'completed'], name='elearning_u_task_id_35ddf5_idx'),
        ),
        migrations.AddIndex(
            model_name='usertaskprogress',
            index=models.Index(fields=['completed_at'], name='elearning_u_complet_497fdc_idx'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='elearning_article',
        ),
        migrations.AlterModelTable(
            name='content',
            table='elearning_content',
        ),
        migrations.AlterModelTable(
            name='module',
            table='elearning_module',
        ),
        migrations.AlterModelTable(
            name='moduleaccess',
            table='elearning_module_access',
        ),
        migrations.AlterModelTable(
            name='modulecategory',
            table='elearning_module_category',
        ),
        migrations.AlterModelTable(
            name='supplementarycontent',
            table='elearning_supplementary_content',
        ),
        migrations.AlterModelTable(
            name='task',
            table='elearning_task',
        ),
        migrations.AlterModelTable(
            name='usertaskprogress',
            table='elearning_user_task_progress',
        ),
    ]
