# Generated by Django 5.1.7 on 2025-08-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0009_add_article_images'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='articleimage',
            name='elearning_a_article_7b9fd3_idx',
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='article',
        ),
    ]
