# Generated by Django 5.1.7 on 2025-08-07 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "elearning",
            "0010_remove_articleimage_elearning_a_article_7b9fd3_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={
                "ordering": ["chapter", "order", "title"],
                "verbose_name": "Learning Content",
                "verbose_name_plural": "Learning Contents",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["chapter", "order", "title"],
                "verbose_name": "Programming Task",
                "verbose_name_plural": "Programming Tasks",
            },
        ),
        migrations.AlterField(
            model_name="content",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Order of content within the chapter (0 = first)",
                verbose_name="Display Order",
            ),
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Descriptive title for this chapter",
                        max_length=255,
                        verbose_name="Chapter Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the chapter content",
                        verbose_name="Description",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of chapters within the module (0 = first)",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this chapter is active and visible to users",
                        verbose_name="Active",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        help_text="Module this chapter belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="elearning.module",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chapter",
                "verbose_name_plural": "Chapters",
                "db_table": "elearning_chapter",
                "ordering": ["module", "order", "title"],
                "unique_together": {("module", "title")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="content",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="content",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                help_text="Chapter this content belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="elearning.chapter",
                verbose_name="Chapter",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                help_text="Chapter this task belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="elearning.chapter",
                verbose_name="Chapter",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="content",
            unique_together={("chapter", "title")},
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("chapter", "title")},
        ),
        migrations.RemoveField(
            model_name="content",
            name="module",
        ),
        migrations.RemoveField(
            model_name="task",
            name="module",
        ),
    ]
