# Generated by Django 5.1.7 on 2025-08-07 06:54

import elearning.modules.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0011_alter_content_options_alter_task_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.CharField(
                help_text="URL to the external article or resource.",
                max_length=500,
                validators=[elearning.modules.models.validate_cloud_url],
                verbose_name="Article URL",
            ),
        ),
    ]
