# Generated by Django 5.2.4 on 2025-08-19 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0013_change_all_url_fields_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='Chapter this article belongs to (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='elearning.chapter', verbose_name='Chapter'),
        ),
    ]
