# Generated by Django 5.2.4 on 2025-09-17 18:15

import django.db.models.deletion
from django.db import migrations, models


def set_missing_chapters(apps, schema_editor):
    Content = apps.get_model("elearning", "Content")
    Chapter = apps.get_model("elearning", "Chapter")
    Module = apps.get_model("elearning", "Module")
    ModuleCategory = apps.get_model("elearning", "ModuleCategory")

    if not Content.objects.filter(chapter__isnull=True).exists():
        return

    # Falls kein Chapter vorhanden, eines erstellen (ForeignKey-Constraint)
    first_chapter = Chapter.objects.order_by("id").first()
    if not first_chapter:
        first_module = Module.objects.first()
        if not first_module:
            # Default Category erstellen, falls nicht vorhanden
            default_category, _ = ModuleCategory.objects.get_or_create(name="Sonstiges")

            # Falls kein Modul vorhanden, eines erstellen (ForeignKey-Constraint)
            first_module = Module.objects.create(
                title="Default Module for Migration",
                category_id=default_category.id,
                is_public=True,
            )
        # Chapter erstellen und mit Modul verknüpfen
        first_chapter = Chapter.objects.create(
            title="Default Chapter for Migration",
            module=first_module,
            description="Default Chapter for Migration",
            order=0,
            is_active=True,
        )

    # Alle Contents ohne Chapter auf dieses Chapter setzen,
    Content.objects.filter(chapter__isnull=True).update(chapter=first_chapter)


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0013_change_all_url_fields_to_charfield"),
    ]

    operations = [
        migrations.RunPython(set_missing_chapters, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="content",
            name="chapter",
            field=models.ForeignKey(
                help_text="Chapter this content belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="elearning.chapter",
                verbose_name="Chapter",
            ),
        ),
    ]
