# Generated by Django 5.1.7 on 2025-11-07 13:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0014_alter_content_chapter"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadableResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("ipynb", "Jupyter Notebook"),
                            ("code", "Code File"),
                            ("slides", "Slides"),
                            ("image", "Image"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "cloud_key",
                    models.CharField(
                        help_text="S3/Wsabi object key,  e.g. Lerninhalte/SQL/Notebooks/intro.ipynb",
                        max_length=1024,
                    ),
                ),
                (
                    "cloud_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional URL for previewing or accessing the resource directly.",
                        max_length=2048,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="Optional ETag/MD5/SHA1 for integrity",
                        max_length=128,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="elearning.article",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="elearning.module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Downloadable Resource",
                "verbose_name_plural": "Downloadable Resources",
                "indexes": [
                    models.Index(
                        fields=["module", "resource_type"],
                        name="elearning_d_module__501626_idx",
                    ),
                    models.Index(
                        fields=["article"], name="elearning_d_article_9e8d24_idx"
                    ),
                    models.Index(
                        fields=["cloud_key"], name="elearning_d_cloud_k_b92c2a_idx"
                    ),
                ],
            },
        ),
    ]
