# Generated by Django 5.2.4 on 2025-08-19 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0014_add_chapter_to_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['chapter', 'order', 'title'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_config',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='test_file_path',
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Description and instructions for the task', verbose_name='Task Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of tasks within the chapter', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Descriptive title for the task', max_length=255, verbose_name='Task Title'),
        ),
        migrations.CreateModel(
            name='TaskMultipleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The multiple choice question text', verbose_name='Question')),
                ('option_1', models.CharField(help_text='First answer option', max_length=500, verbose_name='Option 1')),
                ('option_2', models.CharField(help_text='Second answer option', max_length=500, verbose_name='Option 2')),
                ('option_3', models.CharField(help_text='Third answer option', max_length=500, verbose_name='Option 3')),
                ('option_4', models.CharField(help_text='Fourth answer option', max_length=500, verbose_name='Option 4')),
                ('correct_answer', models.PositiveSmallIntegerField(choices=[(0, 'Option 1'), (1, 'Option 2'), (2, 'Option 3'), (3, 'Option 4')], help_text='Index of the correct answer (0-3)', verbose_name='Correct Answer')),
                ('explanation', models.TextField(blank=True, help_text='Optional explanation for the correct answer', null=True, verbose_name='Explanation')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of questions within the task', verbose_name='Display Order')),
                ('task', models.ForeignKey(help_text='Task this multiple choice question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_questions', to='elearning.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Multiple Choice Question',
                'verbose_name_plural': 'Multiple Choice Questions',
                'db_table': 'elearning_task_multiple_choice',
                'ordering': ['task', 'order'],
            },
        ),
    ]
