# Generated by Django 5.2.4 on 2025-08-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0015_alter_task_options_remove_task_task_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmultiplechoice',
            name='explanation',
        ),
    ]
