# Generated by Django 5.1.7 on 2025-08-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0016_remove_taskmultiplechoice_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('programming', 'Programming Exercise')], default='multiple_choice', help_text='Type of task', max_length=50, verbose_name='Task Type'),
        ),
    ]
