# Generated by Django 5.1.7 on 2025-07-09 12:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0002_employee_email_employee_employees_e_email_8f5bbc_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "frontend_url",
                    models.URLField(
                        blank=True,
                        help_text="URL des zugehörigen Frontends (z.B. http://localhost:5174)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tool",
                "verbose_name_plural": "Tools",
                "ordering": ["slug"],
            },
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(
                help_text="Geschäftliche E-Mail-Adresse des Mitarbeiters",
                max_length=254,
                unique=True,
                verbose_name="E-Mail-Adresse",
            ),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Gearbeitete Stunden am angegebenen Datum (z. B. 7.5)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                        verbose_name="Arbeitsstunden",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.department",
                        verbose_name="Abteilung",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="employees.employee",
                        verbose_name="Mitarbeiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anwesenheit",
                "verbose_name_plural": "Anwesenheiten",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["employee", "date"],
                        name="employees_a_employe_030d17_idx",
                    ),
                    models.Index(
                        fields=["department", "date"],
                        name="employees_a_departm_37db15_idx",
                    ),
                ],
                "unique_together": {("employee", "date")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeToolAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_access",
                        to="employees.employee",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_tool_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_access",
                        to="employees.tool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool-Freigabe",
                "verbose_name_plural": "Tool-Freigaben",
                "ordering": ["-granted_at"],
                "unique_together": {("employee", "tool")},
            },
        ),
    ]
