# Generated by Django 5.1.7 on 2025-07-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shift_planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftschedule",
            name="activity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TA", "Trainingsaktivität"),
                    ("D", "Dozent"),
                    ("D/TA", "D und TA kombiniert"),
                ],
                help_text="Optionaler Aktivitätscode (TA, D, D/TA)",
                max_length=5,
                verbose_name="Aktivität",
            ),
        ),
        migrations.AddField(
            model_name="shiftschedule",
            name="groups",
            field=models.CharField(
                blank=True,
                help_text="Optionale Gruppenangabe (z. B. '5 / 6 / 7')",
                max_length=50,
                verbose_name="Gruppen",
            ),
        ),
    ]
