name: run_tests

on:
  push


jobs:
  django-unittests:
    runs-on: ubuntu-latest
    steps:
      - name: install requirements
        run: |
          python3 install -r requirements.txt
      - name: collect static files
        run: |
          python3 manage.py collectstatic

      - name: run unittests
        run: |
          python3 manage.py test