name: setting_up

on:
  workflow_dispatch:


jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Find out if Action is different
        run: |
          echo This is a different action